import type { Locale } from "./i18n";

/**
 * Each language has its own wordmark: "Just have a little meaning" in English,
 * "po prostu sens" in Polish. Both are generated by
 * `npx tsx src/scripts/generate-logo.ts`.
 */
export function logoSvgPath(locale: Locale): string {
  return locale === "pl" ? "/logo-pl.svg" : "/logo.svg";
}

/** Raster copy, used for structured data. */
export function logoPngPath(locale: Locale): string {
  return locale === "pl" ? "/logo-pl.png" : "/logo.png";
}

/** Wordmark as text, for alt attributes. */
export function logoAlt(locale: Locale): string {
  return locale === "pl" ? "po prostu sens" : "Just have a little meaning";
}
